### ISSUE TITLE
Use-cases for Arbitrary Message Signing

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/community-meeting#1]
**Topic:**

A few questions from community on [Arbitrary Message Signing](https://www.hiro.so/blog/how-arbitrary-message-signing-works-in-the-hiro-wallet).

+ _I am a developer working on dynamic DAO creation and its lifecycle management. I would like to understand how arbitrary message signing would be helpful for our use cases._

+ _I am a developer using client-side authentication through Hiro Wallet. I'd like to understand how message signing would apply to server-side authentication and what tools/utilities are provided by Hiro._

+ _As a game developer working on desktop games, can I use message signing to authenticate or authorize between Hiro Desktop Wallet and my desktop game application?_

**Why this Topic?**

Given the variety of use-cases and the related questions that we see the community asking, it'd be helpful to describe the purpose of this new feature, its value proposition, and what use-case works or not. And what is coming?

**Comment by jdbender66** [comment]
Loving these questions. There is always a chasm between new technological upgrades, and then actually utilizing them to build new features. I can definitely see how arbitrary message signing could help with operations of a complex DeFi suite or DAO governance. Looking forward to discussing in the monthly call!

**Comment by sabbyanandan** [comment]
The supported use-cases were discussed live on the May 26th call (see: [notes / recording](https://github.com/hirosystems/community-meeting/blob/main/notes/May_2022_Meeting_Notes.md)). A few follow-up questions were answered live, as well.
