### ISSUE TITLE
Hyperchains architecture overview

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/community-meeting#2]
**Topic:**

A few questions on Hyperchains:

+ _I am confused about Hyperchains and how it will work. (see: https://twitter.com/axopoa/status/1520812976223264772)_

+ _Hyperchains: what is it, what use-cases would benefit from it, and when will it be ready?_

**Why this topic?**

A general update on Hyperchains, its architecture components (details on deployment topology), and the relevant use-cases would be a helpful topic for the community to discuss.

**Comment by jdbender66** [comment]
Wow thanks for sharing that tweet! Loving the infographic they shared. 
![FRsDVJ4WYAU_LnA](https://user-images.githubusercontent.com/10453432/169298652-7ea085fd-cb91-4500-a1ba-1a08214c3381.jpeg)

**Comment by sabbyanandan** [comment]
An architecture overview was presented by @saralab on the May 26th call (see: [notes/recording](https://github.com/hirosystems/community-meeting/blob/main/notes/May_2022_Meeting_Notes.md)). The roadmap + timeline specifics were part of the discussion also.
